name: build âš™ï¸

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements ğŸ“¦
      run: |
        sudo apt-get update
        sudo apt-get install -y binutils libproj-dev gdal-bin libgdal-dev libsqlite3-mod-spatialite spatialite-bin
        pip install -r requirements-test.txt
        pip install -r requirements-dev.txt
        pip install pygdal=="`gdal-config --version`.*"
        pip install .
    - name: Run unit tests âš™ï¸
      run: |
        pytest
        cd tests/django_test
        python manage.py test testapp
        cd ../sqlalchemy_test/
        python3 -m unittest
        cd ../..
        flake8 pygeofilter

